# Generated by Django 2.0.1 on 2018-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='No heading given')),
                ('content', models.TextField(default='News Content')),
                ('summarized_data', models.TextField(default='Summary')),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('TG', 'Telugu')], default='EN', max_length=2)),
                ('date_of_post', models.DateTimeField(verbose_name='News Creation Date')),
                ('source_link', models.TextField(default='None')),
            ],
        ),
    ]
