# Generated by Django 2.0.1 on 2018-02-15 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscontent',
            name='date_of_post',
        ),
        migrations.AddField(
            model_name='newscontent',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 15, 56, 6, 672213)),
        ),
        migrations.AddField(
            model_name='newscontent',
            name='post_date',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
