# Generated by Django 2.0.1 on 2018-02-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuri', '0006_auto_20180215_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontent',
            name='image_link',
            field=models.URLField(default='/images/no-image.png', max_length=50),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='date_added',
            field=models.DateTimeField(verbose_name='The time details'),
        ),
    ]
