# Generated by Django 2.0.1 on 2018-02-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuri', '0007_auto_20180215_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='image_link',
            field=models.URLField(default='/images/no-image.png', max_length=1000),
        ),
    ]
