# Generated by Django 2.0.1 on 2018-02-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuri', '0008_auto_20180215_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='post_date',
            field=models.DateTimeField(verbose_name='Post Addition Date'),
        ),
    ]
