# Generated by Django 2.0.1 on 2018-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samuri', '0009_auto_20180216_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscontent',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('ur', 'Urdu')], default='EN', max_length=2),
        ),
    ]
